### ISSUE TITLE
possible in the opposite?

### ISSUE THREAD

**Issue by brasileric** [axllent/silverstripe-trailing-slash#1]
Hi,
This is what I need, but than in the opposite: always remove the traling slash. Because of existing social media links which are known without traling slash for the counting.
Is that possible with your script?
I already tried with .htaccess which works, but gives other unexpected issues.

Thanks.

**Comment by axllent** [comment]
Hi,

Well theoretically yes, it could be done. But all your internal SilverStripe links have a slash (hence your site will end up redirecting every internal link), or have you changed that?

**Comment by brasileric** [comment]
I did some changes in your code and now it does what I want. Thanks!
