### ISSUE TITLE
Use HTTPMiddleware for SS4

### ISSUE THREAD

**Issue by dhensby** [axllent/silverstripe-trailing-slash#6]
SilverStripe 4 introduces the [`HTTPMiddleware` interface](https://docs.silverstripe.org/en/4/developer_guides/controllers/middlewares/), which allows modules to hook into the request process at an earlier stage in the request handling process.

This makes re-writing URLs faster (as we don't rely on resolving the full URL to a controller, fetching the model and instantiating the controller(s)) that using an `Extension` as this module currently does.

**Comment by axllent** [comment]
Thanks for the pointer Daniel - appreciated!
