### ISSUE TITLE
Use config system to define list of ignored URLs for extensibility

### ISSUE THREAD

**Issue by michalkleiner** [axllent/silverstripe-trailing-slash#8]
Instead of hardcoding the ignored patterns, these could be defined via the standard config system in a yaml file. With that, developers can provide custom paths for exclusion. Alternatively, a pre-redirect kind of hook would suffice as well to be able to return true/false for a given URL.

**Comment by axllent** [comment]
That is a good idea, although I'm a bit concerned as to how to deal with bad user configs (ie: broken regex or dealing with wildcards etc). Do you have a situation whereby you require alternate paths to be skipped, and can you give me an example of what you would want in terms of config syntax to deal with that?

**Comment by michalkleiner** [comment]
I'd be happy with just adding fixed paths, although you can validate regex by using something like `preg_match($regex, null) !== false)` for a valid one.

Exceptions I can see that handy are any static files served via PHP and anything where it gets to the middleware and is not desirable to have a trailing slash.

Basically, the majority I would still want to ensure is with the slash, but there are, sometimes, exceptions, which would be fine to be able to exclude as well as `/admin` and `/dev`. This time it was `/graphql` for the GraphQL endpoint.

**Comment by axllent** [comment]
I've just released 2.2.0 which contains an optional yaml configuration which should hopefully do what you need. Please test when you can and let me know?
